In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/ Next_word_prediction/qoute_dataset.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes=df['quote']
quotes

0       “The world as we have created it is a process ...
1       “It is our choices, Harry, that show what we t...
2       “There are only two ways to live your life. On...
3       “The person, be it gentleman or lady, who has ...
4       “Imperfection is beauty, madness is genius and...
                              ...
3033        The past beats inside me like a second heart.
3034    Damn, Claire. Warn a guy before you do a face-...
3035    Can you be a girl for a few seconds?""I'm alwa...
3036    That's what fiction is for. It's for getting a...
3037    If we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [ ]:
quotes = quotes.str.lower()

In [ ]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

vocab_size = 8978

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [ ]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
sequence = tokinizer.texts_to_sequences(quotes)

In [ ]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [ ]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [ ]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [ ]:
len(X)

85270

In [ ]:
len(y)

85270

In [ ]:
max_len=max(len(x) for x in X)
print(max_len)

745

In [ ]:

from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [ ]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [ ]:
y=np.array(y)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [ ]:
y.shape

(85270,)

In [ ]:
y_one_hot.shape

(85270, 8978)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [ ]:
embedding_dim = 50
rnn_units = 128

In [ ]:
rnn_model=Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
rnn_model.add(
    SimpleRNN(units=rnn_units, activation='tanh', return_sequences=False)
)
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
rnn_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs=100
batch_size=128

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

# 1. Define the early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',     # Quantity to be monitored
    patience=5,             # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True # Restores model weights from the epoch with the best value
)

In [ ]:
history_rnn = rnn_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 45s 75ms/step - accuracy: 0.0435 - loss: 6.7016 - val_accuracy: 0.0572 - val_loss: 6.6317
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.0728 - loss: 6.1708 - val_accuracy: 0.0792 - val_loss: 6.4800
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.0948 - loss: 5.8316 - val_accuracy: 0.0952 - val_loss: 6.3467
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1104 - loss: 5.5501 - val_accuracy: 0.0998 - val_loss: 6.3677
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1227 - loss: 5.3008 - val_accuracy: 0.1039 - val_loss: 6.4422
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1348 - loss: 5.0732 - val_accuracy: 0.1078 - val_loss: 6.4743
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1474 - loss: 4.8571 - val_accuracy: 0.1067 - val_loss: 6.5275
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1620 - loss: 4.6525 - val_accuracy: 0.1083 - val_loss: 6.6197

In [ ]:
early_stopping = EarlyStopping(
    monitor='val_accuracy',   # Changed to track validation accuracy
    patience=10,              # Increased patience to give the model more time to learn
    mode='max',               # Training stops when accuracy stops INCREASING
    restore_best_weights=True # Keeps the weights from the highest accuracy epoch
)

In [ ]:
history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 39s 60ms/step - accuracy: 0.0389 - loss: 6.7495 - val_accuracy: 0.0427 - val_loss: 6.7306
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.0553 - loss: 6.3220 - val_accuracy: 0.0635 - val_loss: 6.6369
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.0764 - loss: 6.0749 - val_accuracy: 0.0824 - val_loss: 6.5265
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.0939 - loss: 5.8706 - val_accuracy: 0.0888 - val_loss: 6.5143
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1066 - loss: 5.6926 - val_accuracy: 0.0961 - val_loss: 6.5111
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1169 - loss: 5.5167 - val_accuracy: 0.0999 - val_loss: 6.5004
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1259 - loss: 5.3579 - val_accuracy: 0.1053 - val_loss: 6.5256
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1330 - loss: 5.2122 - val_accuracy: 0.1063 - val_loss: 6.5673
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1401 - loss: 5.0773 - val_accuracy: 0.1075 - val_loss: 6.6020
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1463 - loss: 4.9483 - val_accuracy: 0.1087 - val_loss: 6.6516
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1536 - loss: 4.8243 - val_accuracy: 0.1095 - val_loss: 6.7022
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1601 - loss: 4.7031 - val_accuracy: 0.1095 - val_loss: 6.7704
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1683 - loss: 4.5810 - val_accuracy: 0.1094 - val_loss: 6.8234
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 59ms/step - accuracy: 0.1766 - loss: 4.4620 - val_accuracy: 0.1114 - val_loss: 6.8801
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.1877 - loss: 4.3443 - val_accuracy: 0.1111 - val_loss: 6.9553
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1985 - loss: 4.2290 - val_accuracy: 0.1109 - val_loss: 7.0220
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2114 - loss: 4.1180 - val_accuracy: 0.1080 - val_loss: 7.1001
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.2252 - loss: 4.0083 - val_accuracy: 0.1099 - val_loss: 7.1728
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 59ms/step - accuracy: 0.2387 - loss: 3.9046 - val_accuracy: 0.1105 - val_loss: 7.2569
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2536 - loss: 3.8058 - val_accuracy: 0.1082 - val_loss: 7.3370
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2670 - loss: 3.7134 - val_accuracy: 0.1074 - val_loss: 7.4264
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2814 - loss: 3.6261 - val_accuracy: 0.1067 - val_loss: 7.5018
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 59ms/step - accuracy: 0.2938 - loss: 3.5435 - val_accuracy: 0.1073 - val_loss: 7.5730
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.3053 - loss: 3.4663 - val_accuracy: 0.1048 - val_loss: 7.6604

In [ ]:
history_rnn = rnn_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1102 - loss: 5.5502 - val_accuracy: 0.1014 - val_loss: 6.4240
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 68ms/step - accuracy: 0.1202 - loss: 5.3316 - val_accuracy: 0.1037 - val_loss: 6.4891
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1309 - loss: 5.1201 - val_accuracy: 0.1044 - val_loss: 6.5463
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1429 - loss: 4.9129 - val_accuracy: 0.1062 - val_loss: 6.6301
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1572 - loss: 4.7095 - val_accuracy: 0.1047 - val_loss: 6.6698
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1737 - loss: 4.5132 - val_accuracy: 0.1064 - val_loss: 6.7572
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1932 - loss: 4.3258 - val_accuracy: 0.1031 - val_loss: 6.8155
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.2158 - loss: 4.1477 - val_accuracy: 0.1036 - val_loss: 6.9149
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.2372 - loss: 3.9794 - val_accuracy: 0.1024 - val_loss: 6.9951
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.2596 - loss: 3.8240 - val_accuracy: 0.0998 - val_loss: 7.0625
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.2813 - loss: 3.6785 - val_accuracy: 0.0974 - val_loss: 7.1409
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.3012 - loss: 3.5437 - val_accuracy: 0.0963 - val_loss: 7.2097
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.3221 - loss: 3.4185 - val_accuracy: 0.0948 - val_loss: 7.2837
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.3377 - loss: 3.3010 - val_accuracy: 0.0986 - val_loss: 7.3687
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.3568 - loss: 3.1927 - val_accuracy: 0.0933 - val_loss: 7.4349
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.3734 - loss: 3.0917 - val_accuracy: 0.0932 - val_loss: 7.5047
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.3903 - loss: 2.9960 - val_accuracy: 0.0919 - val_loss: 7.5633
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.4042 - loss: 2.9043 - val_accuracy: 0.0928 - val_loss: 7.6382
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.4164 - loss: 2.8210 - val_accuracy: 0.0908 - val_loss: 7.7014
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.4312 - loss: 2.7419 - val_accuracy: 0.0891 - val_loss: 7.7625
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.4450 - loss: 2.6672 - val_accuracy: 0.0877 - val_loss: 7.8384
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.4569 - loss: 2.5948 - val_accuracy: 0.0844 - val_loss: 7.9422
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.4684 - loss: 2.5271 - val_accuracy: 0.0882 - val_loss: 7.9635
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.4797 - loss: 2.4630 - val_accuracy: 0.0845 - val_loss: 8.0364
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.4921 - loss: 2.4043 - val_accuracy: 0.0854 - val_loss: 8.0914
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.5007 - loss: 2.3487 - val_accuracy: 0.0838 - val_loss: 8.1466
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5119 - loss: 2.2920 - val_accuracy: 0.0840 - val_loss: 8.2043
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5210 - loss: 2.2428 - val_accuracy: 0.0812 - val_loss: 8.2733
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.5319 - loss: 2.1941 - val_accuracy: 0.0840 - val_loss: 8.3755
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5391 - loss: 2.1470 - val_accuracy: 0.0809 - val_loss: 8.4212
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5467 - loss: 2.1047 - val_accuracy: 0.0801 - val_loss: 8.4857
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.5555 - loss: 2.0608 - val_accuracy: 0.0798 - val_loss: 8.5437
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5623 - loss: 2.0190 - val_accuracy: 0.0814 - val_loss: 8.5823
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.5700 - loss: 1.9809 - val_accuracy: 0.0810 - val_loss: 8.6187
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5773 - loss: 1.9465 - val_accuracy: 0.0801 - val_loss: 8.6718
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.5837 - loss: 1.9117 - val_accuracy: 0.0783 - val_loss: 8.7487
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.5911 - loss: 1.8795 - val_accuracy: 0.0789 - val_loss: 8.8210
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.5970 - loss: 1.8417 - val_accuracy: 0.0782 - val_loss: 8.8471
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6033 - loss: 1.8131 - val_accuracy: 0.0751 - val_loss: 8.9227
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6072 - loss: 1.7872 - val_accuracy: 0.0749 - val_loss: 8.9752
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6124 - loss: 1.7563 - val_accuracy: 0.0761 - val_loss: 9.0323
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.6202 - loss: 1.7261 - val_accuracy: 0.0755 - val_loss: 9.0953
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6250 - loss: 1.7050 - val_accuracy: 0.0770 - val_loss: 9.1447
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6293 - loss: 1.6815 - val_accuracy: 0.0765 - val_loss: 9.1973
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6326 - loss: 1.6542 - val_accuracy: 0.0745 - val_loss: 9.2709
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6399 - loss: 1.6296 - val_accuracy: 0.0758 - val_loss: 9.2972
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6433 - loss: 1.6054 - val_accuracy: 0.0770 - val_loss: 9.3339
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6478 - loss: 1.5844 - val_accuracy: 0.0769 - val_loss: 9.4073
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6511 - loss: 1.5670 - val_accuracy: 0.0742 - val_loss: 9.4461
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6530 - loss: 1.5542 - val_accuracy: 0.0717 - val_loss: 9.4703
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.6572 - loss: 1.5288 - val_accuracy: 0.0736 - val_loss: 9.5337
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.6607 - loss: 1.5140 - val_accuracy: 0.0738 - val_loss: 9.5880
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6656 - loss: 1.4931 - val_accuracy: 0.0741 - val_loss: 9.6418
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6686 - loss: 1.4737 - val_accuracy: 0.0715 - val_loss: 9.6938
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6708 - loss: 1.4590 - val_accuracy: 0.0719 - val_loss: 9.7384
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6746 - loss: 1.4427 - val_accuracy: 0.0710 - val_loss: 9.7761
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6768 - loss: 1.4298 - val_accuracy: 0.0728 - val_loss: 9.8287
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6809 - loss: 1.4101 - val_accuracy: 0.0708 - val_loss: 9.8686
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6860 - loss: 1.3909 - val_accuracy: 0.0743 - val_loss: 9.9261
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6881 - loss: 1.3779 - val_accuracy: 0.0712 - val_loss: 9.9631
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6925 - loss: 1.3642 - val_accuracy: 0.0700 - val_loss: 10.0047
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6928 - loss: 1.3516 - val_accuracy: 0.0705 - val_loss: 10.0451
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.6950 - loss: 1.3400 - val_accuracy: 0.0684 - val_loss: 10.0840
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.6972 - loss: 1.3295 - val_accuracy: 0.0716 - val_loss: 10.1301
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7000 - loss: 1.3150 - val_accuracy: 0.0711 - val_loss: 10.1566
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7017 - loss: 1.3050 - val_accuracy: 0.0695 - val_loss: 10.2444
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7052 - loss: 1.2878 - val_accuracy: 0.0694 - val_loss: 10.2638
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7082 - loss: 1.2783 - val_accuracy: 0.0682 - val_loss: 10.2930
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 68ms/step - accuracy: 0.7086 - loss: 1.2708 - val_accuracy: 0.0700 - val_loss: 10.3741
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7123 - loss: 1.2549 - val_accuracy: 0.0693 - val_loss: 10.4014
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7157 - loss: 1.2429 - val_accuracy: 0.0688 - val_loss: 10.4343
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7150 - loss: 1.2352 - val_accuracy: 0.0678 - val_loss: 10.4728
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7174 - loss: 1.2303 - val_accuracy: 0.0685 - val_loss: 10.5177
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7220 - loss: 1.2133 - val_accuracy: 0.0681 - val_loss: 10.5637
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7229 - loss: 1.1999 - val_accuracy: 0.0689 - val_loss: 10.6110
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7253 - loss: 1.1906 - val_accuracy: 0.0679 - val_loss: 10.6472
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7271 - loss: 1.1834 - val_accuracy: 0.0672 - val_loss: 10.6743
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7282 - loss: 1.1773 - val_accuracy: 0.0697 - val_loss: 10.7306
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7320 - loss: 1.1642 - val_accuracy: 0.0668 - val_loss: 10.7829
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7302 - loss: 1.1614 - val_accuracy: 0.0683 - val_loss: 10.8064
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7332 - loss: 1.1538 - val_accuracy: 0.0673 - val_loss: 10.8892
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.7318 - loss: 1.1514 - val_accuracy: 0.0671 - val_loss: 10.9128
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7366 - loss: 1.1353 - val_accuracy: 0.0670 - val_loss: 10.9423
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7373 - loss: 1.1285 - val_accuracy: 0.0674 - val_loss: 10.9751
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 68ms/step - accuracy: 0.7371 - loss: 1.1279 - val_accuracy: 0.0680 - val_loss: 11.0223
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7393 - loss: 1.1211 - val_accuracy: 0.0660 - val_loss: 11.0347
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7387 - loss: 1.1175 - val_accuracy: 0.0667 - val_loss: 11.0798
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7434 - loss: 1.1025 - val_accuracy: 0.0678 - val_loss: 11.1161
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 68ms/step - accuracy: 0.7472 - loss: 1.0867 - val_accuracy: 0.0658 - val_loss: 11.1640
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7454 - loss: 1.0952 - val_accuracy: 0.0657 - val_loss: 11.2019
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7463 - loss: 1.0841 - val_accuracy: 0.0673 - val_loss: 11.2323
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7454 - loss: 1.0870 - val_accuracy: 0.0664 - val_loss: 11.2671
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.7555 - loss: 1.0522 - val_accuracy: 0.0661 - val_loss: 11.3176
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7536 - loss: 1.0535 - val_accuracy: 0.0655 - val_loss: 11.3383
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 67ms/step - accuracy: 0.7526 - loss: 1.0563 - val_accuracy: 0.0648 - val_loss: 11.3684
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7559 - loss: 1.0404 - val_accuracy: 0.0668 - val_loss: 11.4370
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.7571 - loss: 1.0363 - val_accuracy: 0.0668 - val_loss: 11.4561
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7543 - loss: 1.0427 - val_accuracy: 0.0662 - val_loss: 11.4846
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7573 - loss: 1.0320 - val_accuracy: 0.0652 - val_loss: 11.5104
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.7583 - loss: 1.0233 - val_accuracy: 0.0638 - val_loss: 11.5448

In [ ]:
history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2,
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.1860 - loss: 4.3253 - val_accuracy: 0.1087 - val_loss: 7.0355
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.2015 - loss: 4.1964 - val_accuracy: 0.1109 - val_loss: 7.1687
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2140 - loss: 4.0839 - val_accuracy: 0.1088 - val_loss: 7.2939
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2289 - loss: 3.9778 - val_accuracy: 0.1091 - val_loss: 7.3794
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.2428 - loss: 3.8780 - val_accuracy: 0.1094 - val_loss: 7.4800
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2572 - loss: 3.7857 - val_accuracy: 0.1074 - val_loss: 7.5879
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2704 - loss: 3.6980 - val_accuracy: 0.1088 - val_loss: 7.6658
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2817 - loss: 3.6158 - val_accuracy: 0.1058 - val_loss: 7.7636
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.2939 - loss: 3.5389 - val_accuracy: 0.1047 - val_loss: 7.8316
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.3050 - loss: 3.4642 - val_accuracy: 0.1033 - val_loss: 7.9178
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3162 - loss: 3.3951 - val_accuracy: 0.1047 - val_loss: 7.9850
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.3257 - loss: 3.3284 - val_accuracy: 0.1016 - val_loss: 8.0475
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.3381 - loss: 3.2637 - val_accuracy: 0.1020 - val_loss: 8.1108
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.3468 - loss: 3.2018 - val_accuracy: 0.1006 - val_loss: 8.1818
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.3563 - loss: 3.1439 - val_accuracy: 0.1004 - val_loss: 8.2563
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.3653 - loss: 3.0863 - val_accuracy: 0.0977 - val_loss: 8.3057
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.3749 - loss: 3.0304 - val_accuracy: 0.0990 - val_loss: 8.3665
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3832 - loss: 2.9769 - val_accuracy: 0.0962 - val_loss: 8.4429
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 44s 62ms/step - accuracy: 0.3915 - loss: 2.9247 - val_accuracy: 0.0965 - val_loss: 8.5120
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4014 - loss: 2.8739 - val_accuracy: 0.0957 - val_loss: 8.5657
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.4094 - loss: 2.8236 - val_accuracy: 0.0942 - val_loss: 8.6422
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4169 - loss: 2.7769 - val_accuracy: 0.0942 - val_loss: 8.7056
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4245 - loss: 2.7319 - val_accuracy: 0.0918 - val_loss: 8.7572
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4333 - loss: 2.6852 - val_accuracy: 0.0898 - val_loss: 8.8332
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4407 - loss: 2.6417 - val_accuracy: 0.0932 - val_loss: 8.8850
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4501 - loss: 2.5983 - val_accuracy: 0.0912 - val_loss: 8.9457
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4568 - loss: 2.5567 - val_accuracy: 0.0898 - val_loss: 9.0076
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4648 - loss: 2.5157 - val_accuracy: 0.0892 - val_loss: 9.0672
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4721 - loss: 2.4757 - val_accuracy: 0.0911 - val_loss: 9.1237
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4791 - loss: 2.4375 - val_accuracy: 0.0873 - val_loss: 9.1872
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4865 - loss: 2.3987 - val_accuracy: 0.0887 - val_loss: 9.2314
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4949 - loss: 2.3625 - val_accuracy: 0.0861 - val_loss: 9.3022
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5004 - loss: 2.3270 - val_accuracy: 0.0877 - val_loss: 9.3499
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.5074 - loss: 2.2910 - val_accuracy: 0.0859 - val_loss: 9.4116
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5147 - loss: 2.2557 - val_accuracy: 0.0857 - val_loss: 9.4694
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5203 - loss: 2.2213 - val_accuracy: 0.0874 - val_loss: 9.5294
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5275 - loss: 2.1885 - val_accuracy: 0.0879 - val_loss: 9.5970
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5336 - loss: 2.1571 - val_accuracy: 0.0854 - val_loss: 9.6327
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5402 - loss: 2.1253 - val_accuracy: 0.0849 - val_loss: 9.6941
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 58ms/step - accuracy: 0.5462 - loss: 2.0948 - val_accuracy: 0.0850 - val_loss: 9.7502
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5522 - loss: 2.0631 - val_accuracy: 0.0840 - val_loss: 9.8101
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5580 - loss: 2.0349 - val_accuracy: 0.0814 - val_loss: 9.8716
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5627 - loss: 2.0054 - val_accuracy: 0.0828 - val_loss: 9.9332
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5708 - loss: 1.9761 - val_accuracy: 0.0803 - val_loss: 9.9747
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5758 - loss: 1.9491 - val_accuracy: 0.0803 - val_loss: 10.0239
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5800 - loss: 1.9236 - val_accuracy: 0.0797 - val_loss: 10.0923
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5854 - loss: 1.8973 - val_accuracy: 0.0780 - val_loss: 10.1492
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5918 - loss: 1.8708 - val_accuracy: 0.0794 - val_loss: 10.2102
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5957 - loss: 1.8457 - val_accuracy: 0.0795 - val_loss: 10.2537
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.6018 - loss: 1.8198 - val_accuracy: 0.0785 - val_loss: 10.3080
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6058 - loss: 1.7965 - val_accuracy: 0.0791 - val_loss: 10.3720
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6118 - loss: 1.7703 - val_accuracy: 0.0797 - val_loss: 10.3954
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6161 - loss: 1.7493 - val_accuracy: 0.0766 - val_loss: 10.4602
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6215 - loss: 1.7258 - val_accuracy: 0.0783 - val_loss: 10.5093
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.6261 - loss: 1.7046 - val_accuracy: 0.0780 - val_loss: 10.5756
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6312 - loss: 1.6813 - val_accuracy: 0.0764 - val_loss: 10.6083
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6362 - loss: 1.6597 - val_accuracy: 0.0744 - val_loss: 10.6609
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.6398 - loss: 1.6386 - val_accuracy: 0.0765 - val_loss: 10.7146
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6441 - loss: 1.6194 - val_accuracy: 0.0758 - val_loss: 10.7588
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6491 - loss: 1.5978 - val_accuracy: 0.0757 - val_loss: 10.8243
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6529 - loss: 1.5778 - val_accuracy: 0.0737 - val_loss: 10.8632
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6565 - loss: 1.5582 - val_accuracy: 0.0764 - val_loss: 10.9193
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6608 - loss: 1.5385 - val_accuracy: 0.0748 - val_loss: 10.9795
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.6651 - loss: 1.5207 - val_accuracy: 0.0752 - val_loss: 11.0120
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6693 - loss: 1.5034 - val_accuracy: 0.0731 - val_loss: 11.0771
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6733 - loss: 1.4826 - val_accuracy: 0.0723 - val_loss: 11.1222
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.6762 - loss: 1.4658 - val_accuracy: 0.0740 - val_loss: 11.1751
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6813 - loss: 1.4484 - val_accuracy: 0.0729 - val_loss: 11.2176
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6841 - loss: 1.4322 - val_accuracy: 0.0746 - val_loss: 11.2733
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6871 - loss: 1.4153 - val_accuracy: 0.0720 - val_loss: 11.3231
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6916 - loss: 1.3995 - val_accuracy: 0.0726 - val_loss: 11.3478
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6952 - loss: 1.3807 - val_accuracy: 0.0724 - val_loss: 11.3992
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6983 - loss: 1.3643 - val_accuracy: 0.0736 - val_loss: 11.4655
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7019 - loss: 1.3504 - val_accuracy: 0.0734 - val_loss: 11.5071
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7035 - loss: 1.3343 - val_accuracy: 0.0736 - val_loss: 11.5595
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 40s 57ms/step - accuracy: 0.7083 - loss: 1.3193 - val_accuracy: 0.0717 - val_loss: 11.6012
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.7117 - loss: 1.3046 - val_accuracy: 0.0715 - val_loss: 11.6552
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7149 - loss: 1.2899 - val_accuracy: 0.0731 - val_loss: 11.6882
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7187 - loss: 1.2772 - val_accuracy: 0.0718 - val_loss: 11.7480
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7219 - loss: 1.2596 - val_accuracy: 0.0732 - val_loss: 11.7877
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7262 - loss: 1.2455 - val_accuracy: 0.0710 - val_loss: 11.8382
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.7267 - loss: 1.2343 - val_accuracy: 0.0707 - val_loss: 11.8840
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7297 - loss: 1.2205 - val_accuracy: 0.0714 - val_loss: 11.9418
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7331 - loss: 1.2067 - val_accuracy: 0.0696 - val_loss: 11.9799
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7364 - loss: 1.1926 - val_accuracy: 0.0706 - val_loss: 12.0514
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7375 - loss: 1.1810 - val_accuracy: 0.0684 - val_loss: 12.0741
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.7422 - loss: 1.1671 - val_accuracy: 0.0714 - val_loss: 12.1257
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.7449 - loss: 1.1545 - val_accuracy: 0.0695 - val_loss: 12.1618
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.7474 - loss: 1.1441 - val_accuracy: 0.0693 - val_loss: 12.2144
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7500 - loss: 1.1307 - val_accuracy: 0.0690 - val_loss: 12.2470
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7516 - loss: 1.1201 - val_accuracy: 0.0693 - val_loss: 12.2782
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7552 - loss: 1.1076 - val_accuracy: 0.0693 - val_loss: 12.3382
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.7569 - loss: 1.0981 - val_accuracy: 0.0693 - val_loss: 12.3978
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.7602 - loss: 1.0846 - val_accuracy: 0.0697 - val_loss: 12.4280
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7630 - loss: 1.0735 - val_accuracy: 0.0687 - val_loss: 12.4896
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7648 - loss: 1.0624 - val_accuracy: 0.0676 - val_loss: 12.5366
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7680 - loss: 1.0513 - val_accuracy: 0.0681 - val_loss: 12.5652
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7690 - loss: 1.0433 - val_accuracy: 0.0674 - val_loss: 12.6069
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.7717 - loss: 1.0319 - val_accuracy: 0.0682 - val_loss: 12.6470
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7744 - loss: 1.0204 - val_accuracy: 0.0683 - val_loss: 12.7142

In [ ]:
# Save the actual models, NOT the history objects
rnn_model.save('rnn_next_word_model.keras')
print("RNN model saved successfully!")

lstm_model.save('lstm_next_word_model.keras')
print("LSTM model saved successfully!")

RNN model saved successfully!
LSTM model saved successfully!

In [ ]:
import pickle

# Save training history logs
with open('rnn_history.pkl', 'wb') as f:
    pickle.dump(history_rnn.history, f)

with open('lstm_history.pkl', 'wb') as f:
    pickle.dump(history_lstm.history, f)

In [ ]:
from google.colab import files

# Download the model files
files.download('rnn_next_word_model.keras')
files.download('lstm_next_word_model.keras')

FileNotFoundError: Cannot find file: tokenizer.pkl

In [ ]:
import pickle

# 1. Create the tokenizer.pkl file on the cloud server
# MAKE SURE to replace 'tokenizer' with your actual tokenizer variable name if it's different!
with open('tokenizer.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)
print("tokenizer.pkl successfully created!")

tokenizer.pkl successfully created!

In [ ]:
files.download('tokenizer.pkl')

In [108]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [109]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [110]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [111]:

seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

implying

In [112]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [113]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a  human being with a world for a book under a

In [114]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)

In [115]:
files.download('max_len.pkl')